server:
  port: 5000

telegram:
  bot-name: myjava_test_bot
  bot-token: 6074706047:AAHLTonZY_Q4-3XMtvn1Jd-P0dvH72rqAcc
  webhook-path: https://7b62-86-57-161-116.ngrok.io
  adminId: 407731984

eventservice:
  period: 600000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ltb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  liquibase:
    change-log: db/changelog-master.yaml